/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/staging/defender/defender.glb --types --keepnames --simplify --weld  
Author: Delinx (https://sketchfab.com/delinx)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/defender-arcade-9e656531a0ea4b6595d2337a4006a552
Title: Defender Arcade
*/

import { Mesh, MeshStandardMaterial } from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: Mesh
    defaultMaterial_1: Mesh
    defaultMaterial_2: Mesh
    defaultMaterial_3: Mesh
    defaultMaterial_4: Mesh
    defaultMaterial_5: Mesh
    defaultMaterial_6: Mesh
    defaultMaterial_7: Mesh
    defaultMaterial_8: Mesh
  }
  materials: {
    ['Material.001']: MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

const FILE_URL = "https://d1zhlm2vwhu5x.cloudfront.net/models/defender-1705650802/defender-transformed.glb.gz";

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <group name="Collada_visual_scene_group" rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="defaultMaterial" geometry={nodes.defaultMaterial.geometry} material={materials['Material.001']} position={[65.331, 108.547, 20.932]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh name="defaultMaterial_1" geometry={nodes.defaultMaterial_1.geometry} material={materials['Material.001']} position={[68.68, 104.811, 16.598]} rotation={[-Math.PI / 2, 0.157, 0]} scale={100} />
          <mesh name="defaultMaterial_2" geometry={nodes.defaultMaterial_2.geometry} material={materials['Material.001']} position={[78.397, 79.792, 11.451]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh name="defaultMaterial_3" geometry={nodes.defaultMaterial_3.geometry} material={materials['Material.001']} position={[79.462, 77.673, 3.91]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh name="defaultMaterial_4" geometry={nodes.defaultMaterial_4.geometry} material={materials['Material.001']} position={[79.184, 92.306, 3.91]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh name="defaultMaterial_5" geometry={nodes.defaultMaterial_5.geometry} material={materials['Material.001']} position={[57.568, 127.516, 4.144]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh name="defaultMaterial_6" geometry={nodes.defaultMaterial_6.geometry} material={materials['Material.001']} position={[57.568, 127.516, 4.144]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh name="defaultMaterial_7" geometry={nodes.defaultMaterial_7.geometry} material={materials['Material.001']} position={[57.568, 127.516, 4.144]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh name="defaultMaterial_8" geometry={nodes.defaultMaterial_8.geometry} material={materials['Material.001']} position={[37.261, 80.029, 4.15]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(FILE_URL)
